name: dbeaver-ce
summary: Universal Database Manager and SQL Client
description: |
  Free multi-platform database tool for developers, SQL programmers, database administrators and analysts. Supports all popular databases: MySQL PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Derby, etc.
grade: stable
adopt-info: dbeaver-ce

base: core22
confinement: classic
architectures:
- amd64

apps:
  dbeaver-ce:
    command: usr/share/dbeaver-ce/dbeaver
    common-id: dbeaver
    desktop: usr/share/applications/dbeaver-ce.desktop
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA 
      # Fixes occasional crashes on various WMs
      NO_AT_BRIDGE: 1

parts:
  dbeaver-ce:
    source: dbeaver-ce_latest_amd64.deb
    plugin: dump
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - libgtk-3-dev
    stage-packages:
      - libxss1
      - libgconf-2-4
      - libcurl4
      - xdg-utils
      - ibus-gtk3
      - libibus-1.0-5
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
    override-pull: |
      snapcraftctl pull
      # Removes NO_AT_BRIDGE=1 from the source .desktop file; it's set for the snap app itself
      sed -i.bak -e 's|env NO_AT_BRIDGE=1 ||g' $SNAPCRAFT_PART_SRC/usr/share/applications/dbeaver-ce.desktop
    override-build: |
      set -e
      snapcraftctl build
      VERSION=$(echo $SNAPCRAFT_PART_INSTALL/usr/share/dbeaver-ce/plugins/org.jkiss.dbeaver.core_*.jar)
      VERSION="${VERSION##*_}"
      VERSION="${VERSION%.*}"
      snapcraftctl set-version "$VERSION"
      LD_BIND_NOW=1
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-*/lib/security/blacklisted.certs

