package org.jkiss.dbeaver.model.ai;

import org.jkiss.dbeaver.model.ai.engine.AIFunctionCall;
import org.jkiss.dbeaver.model.ai.AIFunctionResult;
import org.junit.Test;

import java.time.LocalDateTime;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;


public class AIMessageTest {

    @Test
    public void testSystemMessage() {
        AIMessage msg = AIMessage.systemMessage("System info");
        assertEquals(AIMessageType.SYSTEM, msg.getRole());
        assertEquals("System info", msg.getContent());
        assertEquals("System info", msg.getDisplayMessage());
    }

    @Test
    public void testUserMessage() {
        AIMessage msg = AIMessage.userMessage("Hello");
        assertEquals(AIMessageType.USER, msg.getRole());
        assertFalse(msg.isAutoGenerated());
    }

    @Test
    public void testAssistantMessage() {
        AIMessage msg = AIMessage.assistantMessage("Reply", null);
        assertEquals(AIMessageType.ASSISTANT, msg.getRole());
    }

    @Test
    public void testWarningMessage() {
        AIMessage msg = AIMessage.warningMessage("Warning!");
        assertEquals(AIMessageType.WARNING, msg.getRole());
    }

    @Test
    public void testErrorMessage() {
        AIMessage msg = AIMessage.errorMessage(new RuntimeException("Boom"));
        assertEquals(AIMessageType.ERROR, msg.getRole());
        assertNotNull(msg.getContent());
    }

    @Test
    public void testUserAutoMessage_isAutoGeneratedTrue() {
        AIMessage msg = AIMessage.userAutoMessage("Prompt", "UI Message");
        assertTrue(msg.isAutoGenerated());
        assertEquals("UI Message", msg.getDisplayMessage());
    }

    @Test
    public void testUserAutoMessage_isAutoGeneratedFalse() {
        AIMessage msg = new AIMessage(AIMessageType.USER, "Same", null);
        assertFalse(msg.isAutoGenerated());
    }

    @Test
    public void testGetDisplayMessageFallback() {
        AIMessage msg = new AIMessage(AIMessageType.USER, "Content", null);
        assertEquals("Content", msg.getDisplayMessage());
    }

    @Test
    public void testRawDisplayMessage() {
        AIMessage msg = new AIMessage(
                AIMessageType.USER,
                "Content",
                "Display",
                LocalDateTime.now(),
                null
        );
        assertEquals("Display", msg.getRawDisplayMessage());
    }

    @Test
    public void testWithContent() {
        AIMessage original = AIMessage.userMessage("Old");
        AIMessage updated = original.withContent("New");

        assertEquals("New", updated.getContent());
        assertEquals(original.getRole(), updated.getRole());
        assertEquals(original.getTime(), updated.getTime());
    }

    @Test
    public void testToString() {
        AIMessage msg = AIMessage.userMessage("Hello");
        assertTrue(msg.toString().contains("Hello"));
    }

    @Test
    public void testFunctionMessageFactory() {
        AIMessage msg = AIMessage.functionMessage("123", "payload", AIMessageType.FUNCTION);
        assertEquals("123", msg.getToolUseID());
        assertEquals(AIMessageType.FUNCTION, msg.getRole());
    }

    @Test
    public void testFunctionCallFactory() {
        AIFunctionCall call = mock(AIFunctionCall.class);
        AIFunctionResult result = mock(AIFunctionResult.class);

        when(result.getValue()).thenReturn("value");

        AIMessage msg = AIMessage.functionCall(call, result);

        assertEquals(AIMessageType.FUNCTION, msg.getRole());
        assertNotNull(msg.getFunctionCall());
        assertNotNull(msg.getFunctionResult());
        assertEquals("value", msg.getDisplayMessage());
    }

    @Test
    public void testConstructorWithTimeAndMeta() {
        LocalDateTime now = LocalDateTime.now();

        AIMessage msg = new AIMessage(
                AIMessageType.USER,
                "Content",
                "Display",
                now,
                null
        );

        assertEquals("Display", msg.getDisplayMessage());
        assertEquals(now, msg.getTime());
    }

    @Test
    public void testGetMetaReturnsNull() {
        AIMessage msg = AIMessage.userMessage("Test");
        assertNull(msg.getMeta());
    }

    @Test
    public void testGetFunctionCallNullWhenNotFunction() {
        AIMessage msg = AIMessage.userMessage("Hello");
        assertNull(msg.getFunctionCall());
        assertNull(msg.getFunctionResult());
    }

    @Test
    public void testAllAccessors() {
        AIMessage msg = AIMessage.systemMessage("Access");

        assertEquals(AIMessageType.SYSTEM, msg.getRole());
        assertEquals("Access", msg.getContent());
        assertNotNull(msg.getTime());
        assertNull(msg.getToolUseID());
    }
}
