package org.jkiss.dbeaver.model.ai;

import org.junit.Test;

import java.time.LocalDateTime;

import static org.junit.Assert.*;

public class AIMessageTest {

    @Test
    public void testSystemMessage() {
        AIMessage msg = AIMessage.systemMessage("System info");
        assertEquals(AIMessageType.SYSTEM, msg.getRole());
        assertEquals("System info", msg.getContent());
    }

    @Test
    public void testUserMessage() {
        AIMessage msg = AIMessage.userMessage("Hello");
        assertEquals(AIMessageType.USER, msg.getRole());
    }

    @Test
    public void testAssistantMessage() {
        AIMessage msg = AIMessage.assistantMessage("Reply", null);
        assertEquals(AIMessageType.ASSISTANT, msg.getRole());
    }

    @Test
    public void testWarningMessage() {
        AIMessage msg = AIMessage.warningMessage("Warning!");
        assertEquals(AIMessageType.WARNING, msg.getRole());
    }

    @Test
    public void testErrorMessage() {
        AIMessage msg = AIMessage.errorMessage(new RuntimeException("Boom"));
        assertEquals(AIMessageType.ERROR, msg.getRole());
        assertNotNull(msg.getContent());
    }

    @Test
    public void testUserAutoMessage_isAutoGeneratedTrue() {
        AIMessage msg = AIMessage.userAutoMessage("Prompt", "UI Message");
        assertTrue(msg.isAutoGenerated());
    }

    @Test
    public void testUserAutoMessage_isAutoGeneratedFalse() {
        AIMessage msg = new AIMessage(AIMessageType.USER, "Same", null);
        assertFalse(msg.isAutoGenerated());
    }

    @Test
    public void testGetDisplayMessageFallback() {
        AIMessage msg = new AIMessage(AIMessageType.USER, "Content", null);
        assertEquals("Content", msg.getDisplayMessage());
    }

    @Test
    public void testWithContent() {
        AIMessage original = AIMessage.userMessage("Old");
        AIMessage updated = original.withContent("New");

        assertEquals("New", updated.getContent());
        assertEquals(original.getRole(), updated.getRole());
    }

    @Test
    public void testToString() {
        AIMessage msg = AIMessage.userMessage("Hello");
        assertTrue(msg.toString().contains("Hello"));
    }

    @Test
    public void testFunctionMessage() {
        AIMessage msg = AIMessage.functionMessage("123", "payload", AIMessageType.FUNCTION);
        assertEquals("123", msg.getToolUseID());
        assertEquals(AIMessageType.FUNCTION, msg.getRole());
    }

    @Test
    public void testConstructorWithTimeAndMeta() {
        LocalDateTime now = LocalDateTime.now();
        AIMessage msg = new AIMessage(
                AIMessageType.USER,
                "Content",
                "Display",
                now,
                null
        );

        assertEquals("Display", msg.getDisplayMessage());
        assertEquals(now, msg.getTime());
    }
    @Test
    public void debugTest() {
        System.out.println("AI TEST EXECUTED");
    }

}
